version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/garbarino-com/cart-ui
    steps:
      - checkout
      - attach_workspace:
          at: ~/garbarino-com/cart-ui
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-{{ .Branch }}
            - yarn-cache-
      - run: yarn install
      - run: yarn install-client
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths: 
            - node_modules
            - client/node_modules
            - server/node_modules
      - persist_to_workspace:
          root: .
          paths: .
  build_client:
      docker:
        - image: circleci/node:8-browsers
      working_directory: ~/garbarino-com/cart-ui
      steps:
        - attach_workspace:
            at: ~/garbarino-com/cart-ui
        - run: yarn install
        - run: yarn install-client
        - run: CI=false yarn build-garba
        - run: CI=false yarn build-compu
        - persist_to_workspace:
            root: .
            paths: .
  deploy_elb:
      machine: true
      working_directory: ~/garbarino-com/cart-ui
      steps:
        - attach_workspace:
            at: ~/garbarino-com/cart-ui
        - run:
          name: Install aws dependencies
          command: |
            sudo apt-get update
            sudo apt-get install awscli
        - run: zip  -r /tmp/app.zip . -x "node_modules/*" -x "client/node_modules/*" -x "server/node_modules/*"
        - run:
          name: Deploy All Branches
          command: |
            if [[ "${CIRCLE_TAG}" =~ CHECKOUT-* ]]; then
              aws s3 cp /tmp/app.zip s3://garbarino-deploys/cart-ui/builds/$CIRCLE_SHA1-SNAPSHOT-$CIRCLE_TAG-$CIRCLE_BUILD_NUM.zip
              aws elasticbeanstalk create-application-version --application-name cart-ui --version-label $CIRCLE_SHA1-$CIRCLE_TAG-$CIRCLE_BUILD_NUM --source-bundle S3Bucket=garbarino-deploys,S3Key=cart-ui/builds/$CIRCLE_SHA1-SNAPSHOT-$CIRCLE_TAG-$CIRCLE_BUILD_NUM.zip --region us-east-1
            elif [ "$CIRCLE_BRANCH" == "develop" ]; then
              aws s3 cp /tmp/app.zip s3://garbarino-deploys/cart-ui/builds/$CIRCLE_SHA1-SNAPSHOT-$CIRCLE_BUILD_NUM.zip
              aws elasticbeanstalk create-application-version --application-name cart-ui --version-label $CIRCLE_SHA1-$CIRCLE_BUILD_NUM-ci --source-bundle S3Bucket=garbarino-deploys,S3Key=cart-ui/builds/$CIRCLE_SHA1-SNAPSHOT-$CIRCLE_BUILD_NUM.zip --region us-east-1
              aws elasticbeanstalk update-environment --environment-name chk-ui-ci --version-label $CIRCLE_SHA1-$CIRCLE_BUILD_NUM-ci --region us-east-1
            fi
workflows:
  version: 2
  build_and_deploy_elb:
    jobs:
      - checkout_code
      - build_client:
          requires:
          - checkout_code
      - deploy_elb:
          requires:
          - build_client
          filters:
            branches:
              only:
                - develop
            tags:
              only: /^CHECKOUT-.*/