export const SET_CURRENT_CART = "SET_CURRENT_CART";
export const SET_CURRENT_PRODUCT_CART = "SET_CURRENT_PRODUCT_CART";
export const SET_CAROUSEL = "SET_CAROUSEL";
export const SET_CURRENT_CART_ERROR = "SET_CURRENT_CART_ERROR";
export const SET_SELECTED_PRODUCT = "SET_SELECTED_PRODUCT";
export const HIDE_GENERAL_LOADING = "HIDE_GENERAL_LOADING";
export const ONLY_RE_RENDER = "ONLY_RE_RENDER";

