export const SET_CURRENT_CART = "SET_CURRENT_CART";
export const SET_CURRENT_PRODUCT_CART = "SET_CURRENT_PRODUCT_CART";
export const SET_CAROUSEL = "SET_CAROUSEL";
export const ADD_PRODUCT_CART = "ADD_PRODUCT_CART";
export const SET_CURRENT_CART_ERROR = "SET_CURRENT_CART_ERROR";
